In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [5]:
df=pd.read_csv("Flipkart_mobile_phones.csv")
df

,Unnamed: 0,Product Name,Sale & Actual Price,Review & Ratings,Offer,Camera,Memory,Battery,Display,Rating Number
0,0,"Samsung Galaxy F07 (Green, 64 GB)","₹9,999₹11,99916% off","4.36,152 Ratings & 367 Reviews",16% off,50MP + 2MP | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5000 mAh Battery,17.02 cm (6.7 inch) HD+ Display,4.3
1,1,"realme P4 Lite (Sea Blue, 128 GB)","₹13,999","4.12,307 Ratings & 124 Reviews",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1
2,2,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,"₹22,999₹24,9998% off","4.41,19,659 Ratings & 7,045 Reviews",8% off,50MP + 13MP | 32MP Front Camera,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,5500 mAh Battery,16.94 cm (6.67 inch) Display,4.4
3,3,"realme P4 Lite (Beach Gold, 128 GB)","₹13,999","4.12,307 Ratings & 124 Reviews",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1
4,4,"IQOO Z11x 5G (Prismatic Green, 128 GB)","₹21,750₹28,99924% off",4.3490 Ratings & 43 Reviews,24% off,50MP Rear Camera,6 GB RAM | 128 GB ROM,7200 mAh Battery,17.02 cm (6.7 inch) Display,4.3
...,...,...,...,...,...,...,...,...,...,...
235,235,"REDMI 15 5G (Frosted White, 128 GB)","₹19,990₹19,999","4.32,263 Ratings & 129 Reviews",No Offer,50MP Rear Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.53 cm (6.9 inch) Display,4.3
236,236,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,"₹24,999","4.473,501 Ratings & 4,942 Reviews",No Offer,50MP + 2MP | 16MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,16.94 cm (6.67 inch) Display,4.4
237,237,"OPPO Reno14 5G (Forest Green, 512 GB)","₹47,999","4.53,939 Ratings & 359 Reviews",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 512 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5
238,238,"OPPO Reno14 5G (Pearl White, 256 GB)","₹44,999","4.53,939 Ratings & 359 Reviews",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 256 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5
239,239,"REDMI A5 (Jaisalmer Gold, 64 GB)","₹8,999","4.18,564 Ratings & 412 Reviews",No Offer,32MP Rear Camera | 8MP Front Camera,3 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5200 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.1

In [6]:
df.drop("Unnamed: 0",axis=1,inplace=True)

In [7]:
df

,Product Name,Sale & Actual Price,Review & Ratings,Offer,Camera,Memory,Battery,Display,Rating Number
0,"Samsung Galaxy F07 (Green, 64 GB)","₹9,999₹11,99916% off","4.36,152 Ratings & 367 Reviews",16% off,50MP + 2MP | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5000 mAh Battery,17.02 cm (6.7 inch) HD+ Display,4.3
1,"realme P4 Lite (Sea Blue, 128 GB)","₹13,999","4.12,307 Ratings & 124 Reviews",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1
2,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,"₹22,999₹24,9998% off","4.41,19,659 Ratings & 7,045 Reviews",8% off,50MP + 13MP | 32MP Front Camera,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,5500 mAh Battery,16.94 cm (6.67 inch) Display,4.4
3,"realme P4 Lite (Beach Gold, 128 GB)","₹13,999","4.12,307 Ratings & 124 Reviews",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1
4,"IQOO Z11x 5G (Prismatic Green, 128 GB)","₹21,750₹28,99924% off",4.3490 Ratings & 43 Reviews,24% off,50MP Rear Camera,6 GB RAM | 128 GB ROM,7200 mAh Battery,17.02 cm (6.7 inch) Display,4.3
...,...,...,...,...,...,...,...,...,...
235,"REDMI 15 5G (Frosted White, 128 GB)","₹19,990₹19,999","4.32,263 Ratings & 129 Reviews",No Offer,50MP Rear Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.53 cm (6.9 inch) Display,4.3
236,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,"₹24,999","4.473,501 Ratings & 4,942 Reviews",No Offer,50MP + 2MP | 16MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,16.94 cm (6.67 inch) Display,4.4
237,"OPPO Reno14 5G (Forest Green, 512 GB)","₹47,999","4.53,939 Ratings & 359 Reviews",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 512 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5
238,"OPPO Reno14 5G (Pearl White, 256 GB)","₹44,999","4.53,939 Ratings & 359 Reviews",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 256 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5
239,"REDMI A5 (Jaisalmer Gold, 64 GB)","₹8,999","4.18,564 Ratings & 412 Reviews",No Offer,32MP Rear Camera | 8MP Front Camera,3 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5200 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.1

In [8]:
sale_price=[]
actual_price=[]
for i in range(df.shape[0]):
    try:
        a=df["Sale & Actual Price"][i].split(df["Offer"][i])[0].split("₹")[1]
        sale_price.append(int(a.replace(",","")))
        try:
           b=df["Sale & Actual Price"][i].split(df["Offer"][i])[0].split("₹")[2]
        except IndexError:
           b=a
        actual_price.append(int(b.replace(",","")))
    except IndexError:
        sale_price.append(df["Sale & Actual Price"][i])
        actual_price.append(df["Sale & Actual Price"][i])

In [9]:
df["Sale Price"]=sale_price
df["Actual Price"]=actual_price

In [10]:
df.drop("Sale & Actual Price",axis=1,inplace=True)

In [11]:
df

,Product Name,Review & Ratings,Offer,Camera,Memory,Battery,Display,Rating Number,Sale Price,Actual Price
0,"Samsung Galaxy F07 (Green, 64 GB)","4.36,152 Ratings & 367 Reviews",16% off,50MP + 2MP | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5000 mAh Battery,17.02 cm (6.7 inch) HD+ Display,4.3,9999,11999
1,"realme P4 Lite (Sea Blue, 128 GB)","4.12,307 Ratings & 124 Reviews",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1,13999,13999
2,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,"4.41,19,659 Ratings & 7,045 Reviews",8% off,50MP + 13MP | 32MP Front Camera,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,5500 mAh Battery,16.94 cm (6.67 inch) Display,4.4,22999,24999
3,"realme P4 Lite (Beach Gold, 128 GB)","4.12,307 Ratings & 124 Reviews",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1,13999,13999
4,"IQOO Z11x 5G (Prismatic Green, 128 GB)",4.3490 Ratings & 43 Reviews,24% off,50MP Rear Camera,6 GB RAM | 128 GB ROM,7200 mAh Battery,17.02 cm (6.7 inch) Display,4.3,21750,28999
...,...,...,...,...,...,...,...,...,...,...
235,"REDMI 15 5G (Frosted White, 128 GB)","4.32,263 Ratings & 129 Reviews",No Offer,50MP Rear Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.53 cm (6.9 inch) Display,4.3,19990,19999
236,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,"4.473,501 Ratings & 4,942 Reviews",No Offer,50MP + 2MP | 16MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,16.94 cm (6.67 inch) Display,4.4,24999,24999
237,"OPPO Reno14 5G (Forest Green, 512 GB)","4.53,939 Ratings & 359 Reviews",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 512 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5,47999,47999
238,"OPPO Reno14 5G (Pearl White, 256 GB)","4.53,939 Ratings & 359 Reviews",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 256 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5,44999,44999
239,"REDMI A5 (Jaisalmer Gold, 64 GB)","4.18,564 Ratings & 412 Reviews",No Offer,32MP Rear Camera | 8MP Front Camera,3 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5200 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.1,8999,8999

In [12]:
splitted_cols=df["Review & Ratings"].str.split("&",expand=True)

In [13]:
df["No of Reviews"]=splitted_cols[0].str.replace(",","").str.extract(r"(\d+)").astype('Int64')
df["No of Ratings"]=splitted_cols[1].str.replace(",","").str.extract(r"(\d+)").astype('Int64')

In [14]:
df.drop("Review & Ratings",axis=1,inplace=True)

In [15]:
df

,Product Name,Offer,Camera,Memory,Battery,Display,Rating Number,Sale Price,Actual Price,No of Reviews,No of Ratings
0,"Samsung Galaxy F07 (Green, 64 GB)",16% off,50MP + 2MP | 8MP Front Camera,4 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5000 mAh Battery,17.02 cm (6.7 inch) HD+ Display,4.3,9999,11999,4,367
1,"realme P4 Lite (Sea Blue, 128 GB)",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1,13999,13999,4,124
2,MOTOROLA Edge 60 Fusion 5G (PANTONE Slipstream...,8% off,50MP + 13MP | 32MP Front Camera,8 GB RAM | 128 GB ROM | Expandable Upto 1 TB,5500 mAh Battery,16.94 cm (6.67 inch) Display,4.4,22999,24999,4,7045
3,"realme P4 Lite (Beach Gold, 128 GB)",No Offer,13MP Rear Camera | 5MP Front Camera,4 GB RAM | 128 GB ROM,6300 mAh Battery,17.14 cm (6.75 inch) HD+ Display,4.1,13999,13999,4,124
4,"IQOO Z11x 5G (Prismatic Green, 128 GB)",24% off,50MP Rear Camera,6 GB RAM | 128 GB ROM,7200 mAh Battery,17.02 cm (6.7 inch) Display,4.3,21750,28999,4,43
...,...,...,...,...,...,...,...,...,...,...,...
235,"REDMI 15 5G (Frosted White, 128 GB)",No Offer,50MP Rear Camera,6 GB RAM | 128 GB ROM,7000 mAh Battery,17.53 cm (6.9 inch) Display,4.3,19990,19999,4,129
236,OPPO K13 5G with 7000mAh and 80W SUPERVOOC Cha...,No Offer,50MP + 2MP | 16MP Front Camera,8 GB RAM | 256 GB ROM,7000 mAh Battery,16.94 cm (6.67 inch) Display,4.4,24999,24999,4,4942
237,"OPPO Reno14 5G (Forest Green, 512 GB)",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 512 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5,47999,47999,4,359
238,"OPPO Reno14 5G (Pearl White, 256 GB)",No Offer,50MP + 8MP + 50MP | 50MP Front Camera,12 GB RAM | 256 GB ROM,6000 mAh Battery,16.74 cm (6.59 inch) Display,4.5,44999,44999,4,359
239,"REDMI A5 (Jaisalmer Gold, 64 GB)",No Offer,32MP Rear Camera | 8MP Front Camera,3 GB RAM | 64 GB ROM | Expandable Upto 2 TB,5200 mAh Battery,17.48 cm (6.88 inch) HD+ Display,4.1,8999,8999,4,412

In [16]:
df.to_csv("Proccessed_Flipkart_mobile_phones.csv")

# Store into MongoDB

In [17]:
from pymongo import MongoClient

In [18]:
client=MongoClient("mongodb://localhost:27017")
db=client["filpkart_database"]
collection=db["mobile_phones"]

In [19]:
data_dict=df.to_dict("records")

In [20]:
collection.insert_many(data_dict)
print("DataFrame inserted")

DataFrame inserted